### ISSUE TITLE
Create Pokedex folder, don't want to import everything

### ISSUE THREAD

**Issue by LeoAuyeung** [BursTheGravity/Team-Fantastic-Baby#2]
I was wondering if there was a way to have a folder called "Pokedex" where we can store all of our Pokemon java files such as Charmander.java and be able to call them via Game.java outside of the folder without having to do 'import Charmander.java' for every single Pokemon that we create.

**Comment by LeoAuyeung** [comment]
Figured it out. I can just do 'import Pokedex.*' which will import all of the files within the 'Pokedex' folder.

**Comment by sungbin-kim98** [comment]
Sounds good
